### ISSUE TITLE
zlib package

### ISSUE THREAD

**Issue by rbitnode** [winlibs/libzip#1]
where to put zlib beacause while building i am getting error that zlib not found.

**Comment by cmb69** [comment]
If you want to build PHP, see https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2.

**Comment by cmb69** [comment]
Oops, you likely want to build libzip, so you have to pass `-DZLIB_INCLUDE_DIR=… -DZLIB_LIBRARY=…` to cmake (it should have complained about these missing defines already).
